# Site settings
title: Servus
email: info@servushotel.eu
description-en: Boutique  Hotel in the country
description-hu: Egy vidéki Boutique Hotel
mailing-en: Sign up for our mailinglist and receive updates about our opening.
mailing-hu: Iratkozzon fel hírlevelünkre, hogy első vengégeink között legyen.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://servushotel.eu" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: "https://www.facebook.com/servushotel"
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: "https://www.instagram.com/servushotel"
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/servushotel"

# Build settings
markdown: kramdown

# Logo settings
logo-image-url: assets/images/logo.svg
